secretkey = "insecure_key_for_dev"

gunicornbind = "0.0.0.0:8000"
gunicornaccesslog = '-'
gunicornaccesslogformat = "%(h)s %(l)s %(u)s %(t)s '%(r)s' %(s)s %(b)s '%(f)s' '%(a)s' in %(D)sµs"
gunicornworkers = 1
gunicornthreads = 1
gunicornreload = true

flaskenv = "development"