on:
  pull_request:
    branches:
    - main
    
jobs:
  check_quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.11
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest
          pip install -r requirements.txt
        
      - name: Install ALeRT
        run: |
          pip install -e .
      
      - name: Formatter gate
        run: |
          black . --check
        
      - name: Test
        run: |
          pytest
        
      
      
      
      
      
